on: push
name: testSecurity
jobs:
  doStuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo ${#MYSECRET} && echo $MYSECRET && echo $MYSECRET | base64
        env:
          MYSECRET: ${{ secrets.MYSECRET }}
